name: Zip File
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: test.md test.txt test/
          dest: ./Pack.zip # eventually this will be in RoDoors/TexturePack
      #- name: Commit files
      #  run: |
      #    git config --local user.name "GStudiosX"
      #    git add ./Pack.zip
      #    git commit -m 
      - name: A
        run: |
          git config --global --add safe.directory /github/workspace
      - name: Push changes # push the output file to your repo
        uses: ludeeus/action-push@0.0.1
        env:
          ACTION_MESSAGE: "Update Pack.zip"
          ACTION_MAIL: "gstudiosx@github.com"
          ACTION_NAME: "GStudiosX"
          ACTION_BRANCH: "main"
