name: Zip File
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: vimtor/action-zip@v1
        with:
          files: test.md test.txt test/
          dest: ./build/Pack.zip # eventually this will be in RoDoors/TexturePack
      - name: Update hash.txt
        run: |
          sha1sum ./build/Pack.zip > ./build/hash.txt
      - name: Push
        run: |
          git config --global user.email "githubactions@github.com"
          git config --global user.name "Github-Actions[bot]"
          git status
          git add ./build/Pack.zip
          git commit -m "Update"
          git push origin main
