name: Zip File
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: vimtor/action-zip@v1
        with:
          files: test.md test.txt test/
          dest: ./build/Pack.zip # eventually this will be in RoDoors/TexturePack
      - name: switching from HTTPS to SSH
        run: git remote set-url origin ${{ secrets.ssh }}
      - name: check for changes
        run: git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: git commit -m "Update"
      - name: fetch from main
        run: git fetch origin main
      - name: push to main
        run: git push origin HEAD:main
