name: Zip File
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: test.md test.txt test/
          dest: ./Pack.zip # eventually this will be in RoDoors/TexturePack
#       - name: Commit files
#         run: |
#           git config --local user.name "GStudiosX"
#           git config --local user.email "gstudiosx@github.com"
#           git add ./Pack.zip
#           git commit -m "Update Pack.zip"
      - name: Pushes to Repository
        uses: tech-thinker/push-to-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.token }}
        with:
          user-name: "github-actions[bot]"
          user-email: github-actions[bot]@users.noreply.github.com
          source-directory: "./build/"
          destination-github-username: "RoDoors"
          destination-repository-name: "Test"
          target-branch: main
          
