name: Zip File
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: test.md test.txt test/
          dest: ./build/Pack.zip # eventually this will be in RoDoors/TexturePack
      - name: Commit Files
        run: |
          git config --local user.name "Github-Actions[bot]"
          git config --local user.email "actions@github.com"
          git config --local github.token ${{ secrets.GITHUB_TOKEN }}
          
          git add ./build
          git commit -m "Update"
      - name: Push
        run: |
          git push
