name: Zip File
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: test.md test.txt test/
          dest: ${{ github.workspace }}/Pack.zip # eventually this will be in RoDoors/TexturePack
